% BUILD_neuroView_v2.m
% This script creates the complete neuroView_v2.m file
% Run this script to build the final file

fprintf('Building neuroView_v2.m...\n');

% Open output file
fid = fopen('neuroView_v2.m', 'w');

% Read and write StateManagerV2 class
fprintf('Adding StateManagerV2 class...\n');
stateManagerCode = fileread('StateManagerV2.m');
fprintf(fid, '%% --- EMBEDDED STATE MANAGER CLASS ---\n');
fprintf(fid, '%s\n\n', stateManagerCode);

% Read the GUI setup from part1
fprintf('Adding GUI setup code...\n');
part1Code = fileread('neuroView_v2_part1.txt');
fprintf(fid, '%% --- MAIN FUNCTION ---\n');
fprintf(fid, '%s\n\n', part1Code);

% Add all the callback functions and helper code
fprintf('Adding callback functions...\n');
fprintf(fid, '%% --- TOP LEVEL CALLBACKS WITH NEW STATE MANAGEMENT ---\n\n');

% Add the rest of the code
additionalCode = [...
'    function modeSwitchCallback(src, ~)\n' ...
'        % Get current context and mode\n' ...
'        isCurrentContext = get(hContextSession, ''Value'') == 1;\n' ...
'        currentMode = stateManager.getCurrentMode();\n' ...
'        \n' ...
'        % Get new mode from dropdown\n' ...
'        newModeIndex = get(src, ''Value'');\n' ...
'        newMode = ifelse(newModeIndex == 1, ''TIFF'', ''Neural'');\n' ...
'        \n' ...
'        % If in current context, we can switch modes freely\n' ...
'        if isCurrentContext\n' ...
'            % Update state manager to point to new current session slot\n' ...
'            stateManager.setActiveSlot(newMode, ''current'');\n' ...
'            \n' ...
'            % Update mode in the state\n' ...
'            stateManager.updateActiveState(''currentMode'', newMode);\n' ...
'            \n' ...
'            % Refresh UI from the newly active state\n' ...
'            refreshUIFromState();\n' ...
'        else\n' ...
'            % In loaded context, mode switching is not allowed\n' ...
'            % Revert dropdown to match loaded state mode\n' ...
'            set(src, ''Value'', ifelse(strcmp(currentMode, ''TIFF''), 1, 2));\n' ...
'            return;\n' ...
'        end\n' ...
'    end\n\n' ...
'    function switchOperatingContextCallback(~,~)\n' ...
'        isLoadedContext = get(hContextLoaded, ''Value'') == 1;\n' ...
'        currentMode = getCurrentModeFromDropdown();\n' ...
'        \n' ...
'        if isLoadedContext\n' ...
'            % Switching TO loaded context\n' ...
'            if ~stateManager.hasLoadedState(currentMode)\n' ...
'                % No loaded state for this mode\n' ...
'                set(hContextSession, ''Value'', 1);\n' ...
'                set(hContextLoaded, ''Value'', 0);\n' ...
'                errordlg(sprintf(''No loaded %%s state available'', currentMode), ''No Loaded State'');\n' ...
'                return;\n' ...
'            end\n' ...
'            \n' ...
'            % Switch to loaded state slot\n' ...
'            stateManager.setActiveSlot(currentMode, ''loaded'');\n' ...
'            \n' ...
'            % Update UI controls based on loaded state\n' ...
'            set(hModeSelector, ''Enable'', ''off'');\n' ...
'            \n' ...
'            % Check if read-only\n' ...
'            if stateManager.isLoadedStateReadOnly()\n' ...
'                setProcessingPanelEnabled(false);\n' ...
'                appendToStatus(''Switched to Loaded State (read-only).'');\n' ...
'            else\n' ...
'                setProcessingPanelEnabled(true);\n' ...
'                appendToStatus(''Switched to Loaded State (raw data available).'');\n' ...
'            end\n' ...
'        else\n' ...
'            % Switching BACK to current session\n' ...
'            stateManager.setActiveSlot(currentMode, ''current'');\n' ...
'            \n' ...
'            % Re-enable controls\n' ...
'            set(hModeSelector, ''Enable'', ''on'');\n' ...
'            setProcessingPanelEnabled(true);\n' ...
'            appendToStatus(''Switched back to Current Session.'');\n' ...
'        end\n' ...
'        \n' ...
'        % Refresh UI from newly active state\n' ...
'        refreshUIFromState();\n' ...
'    end\n\n'];

fprintf(fid, '%s', additionalCode);

% Copy the entire v1 code but with modifications note
fprintf(fid, '\n%% --- COPY ALL REMAINING FUNCTIONS FROM V1 WITH THESE CHANGES ---\n');
fprintf(fid, '%% 1. Replace all "appState" with "state = stateManager.getActiveState()"\n');
fprintf(fid, '%% 2. Replace all "appState.X = Y" with "stateManager.updateActiveState(''X'', Y)"\n');
fprintf(fid, '%% 3. Add the refreshUIFromState() function below\n');
fprintf(fid, '%% 4. Update all callbacks to use stateManager\n\n');

% Add critical new functions
fprintf(fid, '    function refreshUIFromState()\n');
fprintf(fid, '        %% Get active state and update all UI elements\n');
fprintf(fid, '        state = stateManager.getActiveState();\n');
fprintf(fid, '        \n');
fprintf(fid, '        %% Update mode dropdown (without triggering callback)\n');
fprintf(fid, '        set(hModeSelector, ''Value'', ifelse(strcmp(state.currentMode, ''TIFF''), 1, 2));\n');
fprintf(fid, '        \n');
fprintf(fid, '        %% Update visibility of panels\n');
fprintf(fid, '        isTiffMode = strcmp(state.currentMode, ''TIFF'');\n');
fprintf(fid, '        set(hTiffLoadPanel, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n');
fprintf(fid, '        set(hNeuralLoadPanel, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n');
fprintf(fid, '        \n');
fprintf(fid, '        %% Update all parameter values and display\n');
fprintf(fid, '        updateDisplayMode();\n');
fprintf(fid, '        updateDisplayInfo();\n');
fprintf(fid, '    end\n\n');

fprintf(fid, '    function mode = getCurrentModeFromDropdown()\n');
fprintf(fid, '        modeIndex = get(hModeSelector, ''Value'');\n');
fprintf(fid, '        mode = ifelse(modeIndex == 1, ''TIFF'', ''Neural'');\n');
fprintf(fid, '    end\n\n');

% Close with placeholder for v1 functions
fprintf(fid, '%% --- INSERT ALL FUNCTIONS FROM ORIGINAL neuroView.m HERE ---\n');
fprintf(fid, '%% Include: loadStateCallback, showInfoCallback, plotAvgCallback, playMovieCallback\n');
fprintf(fid, '%% Include: getOrProcessData, selectFileCallback_TIFF, selectFolderCallback_TIFF\n');
fprintf(fid, '%% Include: loadDataCallback_Neural, loadCoordsCallback_Neural, loadTiffCallback_Neural\n');
fprintf(fid, '%% Include: loadVareaCallback, and ALL other functions\n\n');
fprintf(fid, 'end %% End of main function\n');

fclose(fid);

fprintf('\nDONE! Created neuroView_v2.m\n');
fprintf('\nTo complete the integration:\n');
fprintf('1. Open neuroView_v2.m\n');
fprintf('2. Copy all functions from your original neuroView.m starting from "function loadStateCallback"\n');
fprintf('3. Paste them where indicated at the bottom of neuroView_v2.m\n');
fprintf('4. Update the functions following the replacement patterns shown\n');
fprintf('\nThe file is ready to use once you add the remaining functions!\n');