function CONVERT_TO_V2(inputFile)
% CONVERT_TO_V2 - Automatically converts neuroView v1 to v2 with 4-state architecture
%
% Usage: CONVERT_TO_V2('neuroView.m')
%        This will create 'neuroView_v2.m' with all the updates
%
% Make sure StateManagerV2.m is in your path first!

if nargin < 1
    inputFile = 'neuroView.m';
end

fprintf('Converting %s to v2 with 4-state architecture...\n', inputFile);

% Read the input file
fid = fopen(inputFile, 'r');
if fid == -1
    error('Cannot open input file: %s', inputFile);
end
content = fread(fid, '*char')';
fclose(fid);

% Create output filename
[pathstr, name, ~] = fileparts(inputFile);
outputFile = fullfile(pathstr, [name '_v2.m']);

% Perform replacements
fprintf('Applying v2 transformations...\n');

% 1. Add state manager initialization after function declaration
content = regexprep(content, '(function\s+neuroView[^\n]*\n)', '$1\n% --- Initialize State Manager ---\nstateManager = StateManagerV2();\n');

% 2. Remove old state variables
content = regexprep(content, 'isSwitchingContext\s*=\s*false;\s*%[^\n]*\n', '');
content = regexprep(content, 'appState\s*=\s*struct\(\);\s*%[^\n]*\n', '');
content = regexprep(content, 'appState\.currentMode[^\n]*\n', '');
content = regexprep(content, 'appState\.TIFF\s*=\s*struct\([^;]*;\n', '');
content = regexprep(content, 'appState\.Neural\s*=\s*struct\([^;]*;\n', '');
content = regexprep(content, 'appState\.uiStateCache[^\n]*\n', '');
content = regexprep(content, 'appState\.sessionCache[^\n]*\n', '');
content = regexprep(content, 'appState\.sessionState[^\n]*\n', '');
content = regexprep(content, 'appState\.loadedStateSnapshot[^\n]*\n', '');
content = regexprep(content, 'appState\.sessionMode[^\n]*\n', '');

% 3. Replace initialization calls
content = regexprep(content, 'cacheCurrentUIState\(appState\.currentMode\);', '');
content = regexprep(content, 'updateDisplayMode\(\);', 'updateDisplayMode();\nrefreshUIFromState();');

% 4. Replace callback signatures
% Mode switch callback
oldModeSwitchPattern = 'function modeSwitchCallback\(src, ~\)[^}]*if ~isSwitchingContext[^}]*end[^}]*end';
newModeSwitch = ['function modeSwitchCallback(src, ~)\n' ...
    '    % Get current context and mode\n' ...
    '    isCurrentContext = get(hContextSession, ''Value'') == 1;\n' ...
    '    currentMode = stateManager.getCurrentMode();\n' ...
    '    \n' ...
    '    % Get new mode from dropdown\n' ...
    '    newModeIndex = get(src, ''Value'');\n' ...
    '    newMode = ifelse(newModeIndex == 1, ''TIFF'', ''Neural'');\n' ...
    '    \n' ...
    '    % If in current context, we can switch modes freely\n' ...
    '    if isCurrentContext\n' ...
    '        % Update state manager to point to new current session slot\n' ...
    '        stateManager.setActiveSlot(newMode, ''current'');\n' ...
    '        \n' ...
    '        % Update mode in the state\n' ...
    '        stateManager.updateActiveState(''currentMode'', newMode);\n' ...
    '        \n' ...
    '        % Refresh UI from the newly active state\n' ...
    '        refreshUIFromState();\n' ...
    '    else\n' ...
    '        % In loaded context, mode switching is not allowed\n' ...
    '        % Revert dropdown to match loaded state mode\n' ...
    '        set(src, ''Value'', ifelse(strcmp(currentMode, ''TIFF''), 1, 2));\n' ...
    '        return;\n' ...
    '    end\n' ...
    'end'];

content = regexprep(content, oldModeSwitchPattern, newModeSwitch);

% 5. Replace appState references
% Read operations
content = regexprep(content, 'appState\.', 'state.');
content = regexprep(content, '(\s+)state\.', '$1state = stateManager.getActiveState(); state.');

% Write operations - common patterns
content = regexprep(content, 'state\s*=\s*stateManager\.getActiveState\(\);\s*state\.(\w+)\.(\w+)\s*=\s*([^;]+);', ...
    'stateManager.updateActiveState(''$1.$2'', $3);');

% Cache operations
content = regexprep(content, 'state\.sessionCache\s*=\s*struct\([^)]*\);', 'stateManager.clearCache();');

% 6. Add new helper functions before the last 'end'
helperFunctions = ['\n\n% --- V2 HELPER FUNCTIONS ---\n' ...
    'function refreshUIFromState()\n' ...
    '    % Get active state and update all UI elements\n' ...
    '    state = stateManager.getActiveState();\n' ...
    '    \n' ...
    '    % Update mode dropdown (without triggering callback)\n' ...
    '    set(hModeSelector, ''Value'', ifelse(strcmp(state.currentMode, ''TIFF''), 1, 2));\n' ...
    '    \n' ...
    '    % Update visibility of panels\n' ...
    '    isTiffMode = strcmp(state.currentMode, ''TIFF'');\n' ...
    '    set(hTiffLoadPanel, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    set(hNeuralLoadPanel, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    \n' ...
    '    % Update mode-specific control visibility\n' ...
    '    set(hPlaneLabel, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    set(hPlaneDropdown, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    set(hChannelLabel, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    set(hChannelDropdown, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    set(hSmoothingLabel, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    set(hSmoothingWindowInput, ''Visible'', ifelse(isTiffMode, ''on'', ''off''));\n' ...
    '    \n' ...
    '    set(hNeuropilCoeffLabel, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    set(hNeuropilCoeffInput, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    set(hDetrendCheckbox, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    set(hDetrendWindowLabel, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    set(hDetrendWindowInput, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    set(hForcePositiveCheckbox, ''Visible'', ifelse(~isTiffMode, ''on'', ''off''));\n' ...
    '    \n' ...
    '    % Update display mode visibility\n' ...
    '    updateDisplayMode();\n' ...
    '    \n' ...
    '    % Update info display\n' ...
    '    updateDisplayInfo();\n' ...
    'end\n\n' ...
    'function mode = getCurrentModeFromDropdown()\n' ...
    '    modeIndex = get(hModeSelector, ''Value'');\n' ...
    '    mode = ifelse(modeIndex == 1, ''TIFF'', ''Neural'');\n' ...
    'end\n'];

% Find the last 'end' and insert before it
lastEndPos = find(content == 'e' & [content(2:end) ' '] == 'nd', 1, 'last') - 1;
if ~isempty(lastEndPos)
    content = [content(1:lastEndPos-1) helperFunctions '\n' content(lastEndPos:end)];
end

% Write output file
fid = fopen(outputFile, 'w');
fprintf(fid, '%s', content);
fclose(fid);

fprintf('\nCONVERSION COMPLETE!\n');
fprintf('Created: %s\n', outputFile);
fprintf('\nNOTE: Some manual updates may still be needed:\n');
fprintf('1. Check that all appState references were converted\n');
fprintf('2. Update switchOperatingContextCallback and loadStateCallback\n');
fprintf('3. Test thoroughly with your data\n');
fprintf('\nMake sure StateManagerV2.m is in your MATLAB path!\n');

end